//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package mirror.kotlin

import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object ComparatorClassInfo: ClassInfo<Comparator<*>> {

   override val kClass: KClass<Comparator<*>> = Comparator::class
   override val modifiers: List<ClassInfo.Modifier> = listOf(ClassInfo.Modifier.Interface, ClassInfo.Modifier.Abstract)
   override val companion: Any? get() = null

   override val implements: List<Type<*>> = listOf(Type<kotlin.Any>(kotlin.Any::class, listOf(), false))

   override val packageName: String = "kotlin"
   override val owner: KClass<*>? = null
   override val ownerName: String? = null

   override val name: String = "Comparator"
   override val annotations: List<AnnotationInfo> = listOf()
   override val enumValues: List<Comparator<*>>? = null

   

   override val fields:List<FieldInfo<Comparator<*>, *>> = listOf()

   override fun construct(map: Map<String, Any?>): Comparator<Any?> = throw NotImplementedError()

}