//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.request

import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object RequestClassInfo: ClassInfo<Request<*>> {

   override val kClass: KClass<Request<*>> = Request::class
   override val modifiers: List<ClassInfo.Modifier> = listOf(ClassInfo.Modifier.Interface, ClassInfo.Modifier.Abstract)
   override val companion: Any? get() = null

   override val implements: List<Type<*>> = listOf(Type<kotlin.Any>(kotlin.Any::class, listOf(), false))

   override val packageName: String = "com.lightningkite.mirror.request"
   override val owner: KClass<*>? = null
   override val ownerName: String? = null

   override val name: String = "Request"
   override val annotations: List<AnnotationInfo> = listOf()
   override val enumValues: List<Request<*>>? = null

   

   override val fields:List<FieldInfo<Request<*>, *>> = listOf()

   override fun construct(map: Map<String, Any?>): Request<Any?> = throw NotImplementedError()

}