//Generated by Lightning Kite's Mirror plugin
//AUTOMATICALLY GENERATED AND WILL BE OVERRIDDEN IF THIS MESSAGE IS PRESENT
package com.lightningkite.mirror.archive.database

import com.lightningkite.mirror.info.*
import kotlin.reflect.KClass

@Suppress("RemoveExplicitTypeArguments", "UNCHECKED_CAST", "USELESS_CAST")
object SuspendMapPutRequestClassInfo: ClassInfo<SuspendMapPutRequest<*,*>> {

   override val kClass: KClass<SuspendMapPutRequest<*,*>> = SuspendMapPutRequest::class
   override val modifiers: List<ClassInfo.Modifier> = listOf(ClassInfo.Modifier.Interface, ClassInfo.Modifier.Abstract)
   override val companion: Any? get() = null

   override val implements: List<Type<*>> = listOf(Type<com.lightningkite.mirror.request.Request<kotlin.Boolean>>(com.lightningkite.mirror.request.Request::class, listOf(TypeProjection(Type<kotlin.Boolean>(kotlin.Boolean::class, listOf(), false), TypeProjection.Variance.INVARIANT)), false), Type<com.lightningkite.mirror.archive.database.SuspendMapServerFunction<Any?, kotlin.Any>>(com.lightningkite.mirror.archive.database.SuspendMapServerFunction::class, listOf(TypeProjection(Type<Any?>(Any::class, listOf(), false), TypeProjection.Variance.INVARIANT), TypeProjection(Type<kotlin.Any>(kotlin.Any::class, listOf(), false), TypeProjection.Variance.INVARIANT)), false))

   override val packageName: String = "com.lightningkite.mirror.archive.database"
   override val owner: KClass<*>? = null
   override val ownerName: String? = null

   override val name: String = "SuspendMapPutRequest"
   override val annotations: List<AnnotationInfo> = listOf()
   override val enumValues: List<SuspendMapPutRequest<*,*>>? = null

   

   override val fields:List<FieldInfo<SuspendMapPutRequest<*,*>, *>> = listOf()

   override fun construct(map: Map<String, Any?>): SuspendMapPutRequest<Any?, kotlin.Any> = throw NotImplementedError()

}